# Generated by Django 4.1.2 on 2022-11-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='benhGan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maBenh', models.CharField(max_length=255)),
                ('timHieuChung', models.TextField()),
                ('nguyenNhan', models.TextField()),
                ('nguyCo', models.TextField()),
                ('dieuTri', models.TextField()),
                ('cheDoSinhHoat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ctDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maDonHang', models.CharField(max_length=255)),
                ('maLa', models.CharField(max_length=255)),
                ('soLuong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ctTinTuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maTinTuc', models.CharField(max_length=255)),
                ('noiDung', models.TextField()),
                ('viTri', models.IntegerField()),
                ('kieuDuLieu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='dangNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maDangNhap', models.CharField(max_length=255)),
                ('matKhau', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='dieuTri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maDieuTri', models.CharField(max_length=255)),
                ('maBenh', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='donHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maDonHang', models.CharField(max_length=255)),
                ('maKhachHang', models.CharField(max_length=255)),
                ('ngayLap', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='laThuoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maLa', models.CharField(max_length=255)),
                ('tenLa', models.CharField(max_length=255)),
                ('tenKhac', models.CharField(max_length=255, null=True)),
                ('tenKhoaHoc', models.CharField(max_length=255)),
                ('moTa', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tinTuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maTinTuc', models.CharField(max_length=255)),
                ('ngayDang', models.DateTimeField()),
                ('tieuDe', models.CharField(max_length=255)),
            ],
        ),
    ]
