# Generated by Django 4.1.2 on 2022-11-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_alter_lathuoc_tenkhac'),
    ]

    operations = [
        migrations.AddField(
            model_name='lathuoc',
            name='cachDung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lathuoc',
            name='giaBan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lathuoc',
            name='maDieuTri',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lathuoc',
            name='phanBo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lathuoc',
            name='soLuongCon',
            field=models.IntegerField(default=0),
        ),
    ]
