# Generated by Django 4.1.2 on 2022-11-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_lathuoc_cachdung_lathuoc_giaban_lathuoc_madieutri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lathuoc',
            name='giaBan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lathuoc',
            name='maDieuTri',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lathuoc',
            name='soLuongCon',
            field=models.IntegerField(),
        ),
    ]
