# Generated by Django 4.1.2 on 2022-12-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0010_alter_luutrufile_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='luuTruFile',
            new_name='clipboard',
        ),
    ]
